Updated Installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,109 @@
-chmod -R 777 src_linux
-cp -r CF ~/.config/sublime-text-3/Packages/User/
-cp -r Buggy---Linux ~/.config/sublime-text-3/Packages/User/
-chmod -R 777 ~/.config/sublime-text-3/Packages/User/CF
-chmod -R 777 ~/.config/sublime-text-3/Packages/User/Buggy---Linux
-cp src_linux/Buggy_* /usr/bin/
+echo "Checking the version of Sublime"
+if [ -d ~/.config/sublime-text-3 ]
+then
+	echo "Changing permission of the commands ...."
+	chmod -R 777 src_linux
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Copying CF to ~/.config/sublime-text-3/Packages/User/ ...."
+	cp -r CF ~/.config/sublime-text-3/Packages/User/
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Copying Buggy---Linux to ~/.config/sublime-text-3/Packages/User/ ...."
+	cp -r Buggy---Linux ~/.config/sublime-text-3/Packages/User/
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Changing permission of the directories ...."
+	
+	chmod -R 777 ~/.config/sublime-text-3/Packages/User/CF
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+	
+	chmod -R 777 ~/.config/sublime-text-3/Packages/User/Buggy---Linux
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Copying commands to /usr/bin ...."
+	cp src_linux/Buggy_* /usr/bin/
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Installation Successful"
+
+elif [ -d ~/.config/sublime-text-2 ]
+then
+	echo "Changing permission of the commands ...."
+	chmod -R 777 src_linux
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Copying CF to ~/.config/sublime-text-2/Packages/User/ ...."
+	cp -r CF ~/.config/sublime-text-2/Packages/User/
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Copying Buggy---Linux to ~/.config/sublime-text-2/Packages/User/ ...."
+	cp -r Buggy---Linux ~/.config/sublime-text-2/Packages/User/
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Changing permission of the directories ...."
+	
+	chmod -R 777 ~/.config/sublime-text-2/Packages/User/CF
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+	
+	chmod -R 777 ~/.config/sublime-text-2/Packages/User/Buggy---Linux
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Copying commands to /usr/bin ...."
+	cp src_linux/Buggy_* /usr/bin/
+	if [ $? -ne 0 ]
+	then
+		echo "Aborting : Error"
+		exit
+	fi
+
+	echo "Installation Successful"
+
+else
+	echo "No Sublime Text found on System at path /.config/sublime-text-x...."
+	echo "Aborting : Error"
+fi
