Add messages to BatchTest

diff --git a/src_linux/BuggyBatchTest b/src_linux/BuggyBatchTest
--- a/src_linux/BuggyBatchTest
+++ b/src_linux/BuggyBatchTest
@@ -1,21 +1,32 @@
-for i in 0 1 2 3 4 5 6 7 8 9 10 11 12
+red='\033[0;31m'
+lightGreen='\033[1;32m'
+noColor='\033[0m'
+
+for (( i=0; i <= 100; i++ ))
 do
-	FILE=in$i.txt
-	OUTFILE=out$i.txt
-	if [ -f $FILE ]; then
-		#echo "exists"
-		echo "Running Test Case " $i
-		echo "\n"
-		echo "Input : "
-		cat $FILE
-		echo "\n"
-		./$1 < in$i.txt > o.txt
-		echo "Your Output : "
-		cat o.txt
-		echo "\n"
-		echo "Correct Output : "
-		cat $OUTFILE
-		echo "\n"
-		echo "----------------------------------------"
+	inFile=in$i.txt
+	outFile=out$i.txt
+
+	if [ -f $inFile ]; then
+		printf "Running Test-case $i : \n"
+		printf "Input : "
+		cat $inFile
+		printf "\n"
+		./$1 < $inFile > o
+		printf "Your Output : "
+		cat o
+		printf "\n"
+		printf "Correct Output : "
+		cat $outFile
+		printf "\n"
+
+		diff -w $outFile o >/dev/null;REPLY=$?
+		if [ ${REPLY} -eq 0 ]
+		then
+		        printf "Exact matching : ${lightGreen}PASS${noColor}\n"
+		else
+		        printf "Exact matching : ${red}FAIL${noColor}\n"
+		fi
+		printf "======================================\n"
 	fi
 done
